from collections.abc import Iterator
from typing import Any


class Design:
    @staticmethod
    def cast(obj: object) -> "Design": ...
    @property
    def rootComponent(self) -> "Component": ...
    @property
    def userParameters(self) -> "UserParameters": ...
    @property
    def timeline(self) -> object: ...
    @property
    def attributes(self) -> object: ...


class Component:
    @property
    def sketches(self) -> "SketchList": ...
    @property
    def bRepBodies(self) -> "BRepBodyList": ...
    @property
    def xZConstructionPlane(self) -> "ConstructionPlane": ...
    @property
    def features(self) -> "Features": ...
    @property
    def constructionPlanes(self) -> "ConstructionPlaneList": ...
    @property
    def xConstructionAxis(self) -> "ConstructionAxis": ...
    @property
    def yConstructionAxis(self) -> "ConstructionAxis": ...
    @property
    def xYConstructionPlane(self) -> "ConstructionPlane": ...


class Sketch:
    @property
    def sketchDimensions(self) -> "SketchDimensionList": ...
    @property
    def geometricConstraints(self) -> "GeometricConstraintList": ...
    @property
    def isFullyConstrained(self) -> bool: ...
    @property
    def sketchPoints(self) -> "SketchPointList": ...
    @property
    def profiles(self) -> "ProfileList": ...
    @property
    def xDirection(self) -> object: ...
    @property
    def sketchCurves(self) -> "SketchCurveList": ...
    @property
    def originPoint(self) -> "SketchPoint": ...

    def sketchToModelSpace(self, point: object) -> object: ...
    def modelToSketchSpace(self, point: object) -> object: ...


class SketchList:
    def item(self, index: int) -> "Sketch": ...
    def add(self, plane: object) -> "Sketch": ...
    @property
    def count(self) -> int: ...


class SketchCurveList:
    @property
    def sketchLines(self) -> "SketchLineList": ...
    @property
    def sketchCircles(self) -> "SketchCircleList": ...


class SketchLineList:
    def addTwoPointRectangle(
        self, point1: object, point2: object
    ) -> "SketchLineCollection": ...
    def item(self, index: int) -> "SketchLine": ...
    @property
    def count(self) -> int: ...


class SketchLine:
    @property
    def startSketchPoint(self) -> "SketchPoint": ...
    @property
    def endSketchPoint(self) -> "SketchPoint": ...


class SketchLineCollection:
    def item(self, index: int) -> "SketchLine": ...
    @property
    def count(self) -> int: ...


class SketchCircleList:
    def addByCenterRadius(self, center: object, radius: float) -> "SketchCircle": ...


class SketchCircle:
    @property
    def centerSketchPoint(self) -> "SketchPoint": ...


class SketchPoint:
    @property
    def geometry(self) -> object: ...


class SketchPointList:
    def item(self, index: int) -> object: ...


class ProfileList:
    def item(self, index: int) -> object: ...


class SketchDimensionList:
    def addDistanceDimension(
        self, point1: object, point2: object, orientation: int, anchor: object
    ) -> "SketchDimension": ...
    def addDiameterDimension(self, circle: object, anchor: object) -> "SketchDimension": ...
    def addFixedDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addEqualDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addSymmetricDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addVerticalDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addHorizontalDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def item(self, index: int) -> "SketchDimension": ...
    @property
    def count(self) -> int: ...


class GeometricConstraintList:
    def addHorizontal(self, curve: object) -> object: ...
    def addVertical(self, curve: object) -> object: ...


class SketchDimension:
    @property
    def parameter(self) -> "Parameter": ...


class Parameter:
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, value: str) -> None: ...


class DimensionOrientations:
    HorizontalDimensionOrientation: int
    VerticalDimensionOrientation: int


class BRepBodyList:
    def item(self, index: int) -> "BRepBody": ...
    def __iter__(self) -> Iterator["BRepBody"]: ...
    @property
    def count(self) -> int: ...


class BRepBody:
    @property
    def faces(self) -> "FaceList": ...
    @property
    def edges(self) -> "EdgeList": ...
    @property
    def volume(self) -> float: ...


class FaceList:
    def item(self, index: int) -> "Face": ...
    def __iter__(self) -> Iterator["Face"]: ...
    @property
    def count(self) -> int: ...


class Face:
    @property
    def geometry(self) -> "Geometry": ...
    @property
    def tempId(self) -> str: ...
    @property
    def area(self) -> float: ...


class Geometry:
    @property
    def normal(self) -> object: ...


class EdgeList:
    def item(self, index: int) -> "Edge": ...


class Edge:
    pass


class UserParameters:
    def add(self, name: str, value: object, units: str, description: str) -> object: ...
    def itemByName(self, name: str) -> "UserParameter": ...


class UserParameter:
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, value: str) -> None: ...
    @property
    def value(self) -> float: ...


class Features:
    @property
    def extrudeFeatures(self) -> "ExtrudeFeatureList": ...
    @property
    def rectangularPatternFeatures(self) -> "RectangularPatternFeatureList": ...


class ExtrudeFeatureList:
    def createInput(self, profiles: object, operation: int) -> "ExtrudeFeatureInput": ...
    def add(self, input_obj: "ExtrudeFeatureInput") -> "ExtrudeFeature": ...
    def item(self, index: int) -> "ExtrudeFeature": ...
    @property
    def count(self) -> int: ...


class ExtrudeFeature:
    @property
    def healthState(self) -> int: ...
    @property
    def bodies(self) -> "BRepBodyList": ...
    def deleteMe(self) -> None: ...


class ExtrudeFeatureInput:
    @property
    def participantBodies(self) -> object: ...
    @participantBodies.setter
    def participantBodies(self, value: object) -> None: ...
    def setSymmetricExtent(self, extent: object, symmetric: bool) -> None: ...
    def setOneSideExtent(self, extent: object, direction: int) -> None: ...


class RectangularPatternFeatureList:
    def createInput(
        self, collection: object, axis: object, count: object, distance: object, distance_type: int
    ) -> "RectangularPatternFeatureInput": ...
    def add(self, input_obj: "RectangularPatternFeatureInput") -> "RectangularPatternFeature": ...
    def item(self, index: int) -> "RectangularPatternFeature": ...


class RectangularPatternFeatureInput:
    @property
    def patternComputeOption(self) -> int | None: ...
    @patternComputeOption.setter
    def patternComputeOption(self, value: int) -> None: ...
    def setDirectionTwo(self, axis: object, count: object, distance: object) -> None: ...


class RectangularPatternFeature:
    @property
    def healthState(self) -> str: ...
    @property
    def bodies(self) -> "BRepBodyList": ...
    def deleteMe(self) -> None: ...


class ConstructionPlaneList:
    def createInput(self) -> "ConstructionPlaneInput": ...
    def add(self, input_obj: "ConstructionPlaneInput") -> "ConstructionPlane": ...
    def item(self, index: int) -> "ConstructionPlane": ...
    @property
    def count(self) -> int: ...


class ConstructionPlaneInput:
    def setByOffset(self, plane: "ConstructionPlane", offset: object) -> None: ...


class ConstructionAxis:
    pass


class ConstructionPlane:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...


class FeatureOperations:
    CutFeatureOperation: int
    JoinFeatureOperation: int
    NewBodyFeatureOperation: int


class DistanceExtentDefinition:
    @staticmethod
    def create(distance: object) -> "DistanceExtentDefinition": ...


class ExtentDirections:
    PositiveExtentDirection: int
    NegativeExtentDirection: int


class FeatureHealthStates:
    HealthyFeatureHealthState: str
    WarningFeatureHealthState: str


class PatternComputeOptions:
    AdjustPatternCompute: int
    IdenticalPatternCompute: int


class PatternDistanceType:
    SpacingPatternDistanceType: int
