from collections.abc import Iterator
from typing import Any


class Design:
    @staticmethod
    def cast(obj: object) -> "Design": ...
    @property
    def rootComponent(self) -> "Component": ...
    @property
    def userParameters(self) -> "UserParameters": ...
    @property
    def timeline(self) -> object: ...
    @property
    def attributes(self) -> object: ...


class Component:
    @property
    def sketches(self) -> "SketchList": ...
    @property
    def bRepBodies(self) -> "BRepBodyList": ...
    @property
    def xZConstructionPlane(self) -> "ConstructionPlane": ...


class Sketch:
    @property
    def sketchDimensions(self) -> "SketchDimensionList": ...
    @property
    def geometricConstraints(self) -> object: ...
    @property
    def isFullyConstrained(self) -> bool: ...
    @property
    def sketchPoints(self) -> "SketchPointList": ...
    @property
    def profiles(self) -> "ProfileList": ...
    @property
    def xDirection(self) -> object: ...

    def sketchToModelSpace(self, point: object) -> object: ...


class SketchList:
    def item(self, index: int) -> "Sketch": ...
    def add(self, plane: object) -> "Sketch": ...
    @property
    def count(self) -> int: ...


class SketchPointList:
    def item(self, index: int) -> object: ...


class ProfileList:
    def item(self, index: int) -> object: ...


class SketchDimensionList:
    def addDistanceDimension(
        self, point1: object, point2: object, orientation: int, anchor: object
    ) -> "SketchDimension": ...
    def addFixedDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addEqualDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addSymmetricDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addVerticalDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def addHorizontalDimension(self, *args: Any, **kwargs: Any) -> "SketchDimension": ...
    def item(self, index: int) -> "SketchDimension": ...
    @property
    def count(self) -> int: ...


class SketchDimension:
    @property
    def parameter(self) -> "Parameter": ...


class Parameter:
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, value: str) -> None: ...


class DimensionOrientations:
    HorizontalDimensionOrientation: int
    VerticalDimensionOrientation: int


class BRepBodyList:
    def item(self, index: int) -> "BRepBody": ...
    def __iter__(self) -> Iterator["BRepBody"]: ...
    @property
    def count(self) -> int: ...


class BRepBody:
    @property
    def faces(self) -> "FaceList": ...
    @property
    def edges(self) -> "EdgeList": ...


class FaceList:
    def item(self, index: int) -> "Face": ...
    def __iter__(self) -> Iterator["Face"]: ...
    @property
    def count(self) -> int: ...


class Face:
    @property
    def geometry(self) -> "Geometry": ...
    @property
    def tempId(self) -> str: ...
    @property
    def area(self) -> float: ...


class Geometry:
    @property
    def normal(self) -> object: ...


class EdgeList:
    def item(self, index: int) -> "Edge": ...


class Edge:
    pass


class ConstructionPlane:
    pass


class UserParameters:
    def add(self, name: str, value: object, units: str, description: str) -> object: ...
    def itemByName(self, name: str) -> "UserParameter": ...


class UserParameter:
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, value: str) -> None: ...
