# Supernova 72 - Flagship Spinner Final Spec

Product of the excellent-spinner workflow (3 analysts, 4 designers, 3 judges, 1 synthesizer), 2026-08-02.


## Final ranking

| # | Design | Brief | Fun | Pizazz | Print | Total /30 |
|---|---|---|---|---|---|---|
| 1 | Supernova | ILLUSION + PHYSICS | 7.7 | 7.3 | 7.7 | 22.7 |
| 2 | Cicada 75 — the spinner that talks back | TACTILE FLAGSHIP | 9 | 5 | 8.7 | 22.7 |
| 3 | Pulsar Bloom 78 | MAXIMUM MOTION | 6.7 | 9 | 4.7 | 20.3 |
| 4 | Ghost Gauge 75 — the print-in-place spinner with a built-in moiré speedometer | WILDCARD | 5.7 | 8 | 6 | 19.7 |

## Final spec: Supernova 72 (Final Build Spec)

### Concept
A print-in-place variable-inertia spinner that appears broken at rest: six signal-orange Ø8 slugs rattle loose in open radial slots, then leap outward within a quarter-turn of a flick and lock against a hidden r33 race, going dead silent and spinning glass-smooth. The flywheel assembles itself at speed (inertia is higher spinning than at rest) and audibly disassembles as the spin dies below ~2.9 rev/s — a built-in spin-decay alarm ending in the death-rattle. This final spec fixes every judge-flagged weakness: the viewing-window crossbar is relocated inboard so the seated ring is 97% unoccluded, the persistence-of-vision orange circle becomes the mid-spin show, all wall/window geometry is re-verified to the 1.6/2.5 mm floors, and a 25-minute test coupon de-risks the roller float gap before the flagship print.

### Pizazz
The 2-second GIF, now with three acts instead of two: (1) top-down, matte-black body, six orange dots slumped at random radii — shake it and it clatters like a failed print; (2) flick — the dots explode outward in sync, visible ring diameter grows 40% (40→58 mm), and because the relocated crossbar leaves the seated band r25–33 clear, motion blur fuses the six slugs into a single continuous orange circle drawn in mid-air — the mid-spin show the draft lacked (blur is now weaponized, not hidden from); (3) spin-down — at ~2.9 rev/s (physics-verified: ω=√(g/0.029)) the circle shatters back into cascading dots with an audible countdown rattle. In hand: 12 rim scallops give a flick landmark every 30°, the seated state has gyroscopic heft that visibly exceeds the at-rest feel, and near the threshold you can tilt the plane to trigger or delay the cascade — a free play mode from pure physics, no geometry cost. Rattle-to-silence-to-rattle is a full sensory lifecycle with zero hardware, in the untouched PiP-audible-feedback whitespace. AMS two-color (slugs as separate bodies) makes every act camera-legible.

### Geometry
Envelope OD 72.0 × H 14.0 mm, flat bottom, 6-fold symmetric, three body classes, one plate. All dims mm; user parameters in [brackets].

STATOR HUB: bottom cap Ø26.0, z0–2.5; journal column base radius 11.0, z2.5–11.5; 45° diamond ridge 1.2 deep (peak r12.2), axial span z5.8–8.2 centered z7.0 (exact verified recipe scale); top cap Ø26.0, z11.5–14.0; spherical finger dimples Ø18 × 1.2 deep on both cap outer faces; 0.4 chamfers on cap circular rims; 0.3 anti-fuse chamfers on both bottom-gap circular edges.

ROTOR: female journal bore r11.25 = base + [c_journal=0.25, variants 0.20/0.30]; internal groove peak r12.45, 45° flanks matching ridge span, 0.3 anti-fuse chamfers both groove bottom edges; journal stack z2.8–11.2 (8.4 mm). Cap counterbores r13.4 × 2.8 deep both ends → 0.4 radial / 0.3 axial cap clearance; counterbore ceiling annulus (r11.25–13.4) bridges 2.15 mm over the 0.3 gap. Sleeve to r16.0. Deck r16–33 full height with 6 radial slots at 60°: width 9.0, span r16–33, floor solid z0–1.2, cavity z1.2–12.4, ceiling z12.4–14.0 (1.6 thick). CEILING WINDOW (revised): opening 5.8 wide (two rails 1.6 wide × 1.6 thick — at the wall floor, maximizing view); ONE crossbar 2.5 wide centered at r24.0 (spans r22.75–25.25), relocated inboard from mid-length so the seated slug band r25–33 is ~97% unoccluded. Rail bridge segments: inner r16–22.75 = 6.75, outer r25.25–33 = 7.75; crossbar bridges 5.8 tangentially — all ≤8 mm. LIGHTENING WINDOWS (re-verified): 6 full-height through-sectors between slots, 17° total (±8.5° about the between-slot bisector), radial span r19–29; min tangential wall to slot = 2.59 at r19 (grows to 6.4 at r29), radial webs 3.0 (r16–19) and 4.0 (r29–33) — draft's 28°/r18–30 violated the 2.5 wall floor and is corrected. RIM r33–36 full height; outer silhouette R(θ) = 35.3 + 0.7·cos(12θ) — crest 36.0, trough 34.6, scallop depth 1.4, min rim wall 1.6 (draft's cos(6θ)/12-scallop mismatch and 1.5 trough wall corrected); race = rim inner cylinder r33.0, perfectly circular, concentric with journal. ROLLERS ×6: Ø[d_roll=8.0] × 10.4, z1.5–11.9 (bottom gap [g_float=0.30, variants 0.25/0.35] above floor, top gap 0.5), 0.3 chamfers both circular ends, printed at rest axis r20.5 on slot centerline; 0.5/side tangential clearance; travel r20.5→29.0; seats as a vertical line contact on the r33 race. All clearances ≥0.25, all walls ≥1.6, no flexures, no detents, no sub-1.2 features.

FUSION 360 BUILD ORDER: (1) User parameters: c_journal, g_float, d_roll, slot_w=9.0, OD=72, H=14, scallop amp 0.7/count 12. (2) Sketch XZ half-profile of hub (cap–column–ridge–cap polyline) → Revolve, body STATOR. (3) Sketch XZ rotor journal half-profile (bore 11.25, groove 12.45, counterbores 13.4×2.8, sleeve OD 16) → Revolve, body ROTOR. (4) Sketch XY at z0: outer scalloped curve as R(θ)=35.3+0.7cos(12θ) sampled ≥73 points → fitted spline (closed); inner circle r16 → Extrude z0–14, Join to ROTOR. (5) Sketch slot rectangle (9.0 wide, r16–33 on X axis) → Extrude-cut z1.2–12.4. (6) Sketch on top face: window 5.8 wide r16–33 minus 2.5 crossbar at r24 → Extrude-cut z12.4–14.0. (7) Sketch 17° sector r19–29 → Extrude-cut through-all. (8) Sketch Ø8 circle at (20.5, 0) → Extrude z1.5–11.9, New Body ROLLER. (9) Circular-pattern ×6 about Z: features 5–7 (pattern features) and body ROLLER (pattern bodies). (10) Revolve-cut spherical dimples both hub cap faces. (11) Chamfers LAST, circular edges ONLY: 0.4 cap rims, 0.3 roller ends, 0.3 anti-fuse pairs, 0.4 bore/counterbore mouths — never touch the scalloped spline outline (ASM_BL_CAP_COMPLEX). (12) Script hygiene: any body cleanup via removeFeatures.add(), never BRepBody.deleteMe() (parametric zombie-resurrection); adsk.doEvents() between feature batches. (13) Verify: interference check all bodies, section analysis at z7.0 (ridge clearance = c_journal all round), mass properties (CoM on axis by construction), export one 3MF with three named body groups for AMS mapping.

### Mass Distribution
~51 g PLA total (1.24 g/cm³, 100% / perimeter-dominant deterministic infill). Rim ring r33–36 × H14 ≈ 11.3 g at r_avg 34.5; deck hollowed by 6 slots + 6 through-sector windows to force volume outward (≥40% of rotor volume beyond 0.8R vs 36% uniform-disk reference); rollers 6 × ~0.72 g = 4.3 g riding at r29 when seated. Rim ratio ~1.2 at rest rising to ~1.25–1.3 seated — the headline physics: the corpus's only spinner whose inertia is HIGHER spinning than at rest. Balance is by construction, no calibration workflow: 6-fold symmetry, six identical rollers, one concentric circular race — a single stranded slug costs ~5 g·mm (perceptible, not disabling) and is caught by the shake-test QA. HEAVY variant: omit printed rollers (exclude bodies in slicer), G-code pause at z12.4 before the rails close, drop six Ø8 chrome bearing balls (2.09 g each, grade-ground so balance is guaranteed) — ball sits z1.2–9.2, clears the z12.4 ceiling; +12.5 g all seating at r29 lifts rotor inertia ~30% to rim ratio ~1.5, beating every palm-size leaderboard design for a 30-second, sub-1-GBP, no-glue insert. Total mass and 72 mm OD sit inside the verified 55–75 mm / under-90 g hand-feel band.

### Print Plan
Single plate, one 3MF, three body groups (STATOR + ROTOR black, 6 ROLLERS signal-orange via AMS; mono-color fallback prints fine — the geometry still reads). Flat-bottom pure 2D-profile extrusions, zero supports, 0.2 mm layers, 4+ perimeters, stock 0.4 nozzle PLA, ~2.5–3 h. Bridges: rail segments 6.75/7.75, crossbar 5.8, counterbore ceilings 2.15 over 0.3 gaps — all ≤8 mm, under the 10 mm rule with margin; set bridge direction detection on. Rollers stand on a [g_float=0.30] horizontal separation gap above the solid slot floor at z1.2 — well above elephant-foot territory (standard PiP planet-gear practice). Anti-strand protocol (answers the judges' top deduction): dry filament, z-hop OFF, avoid-crossing-perimeters ON, combing within infill, 0.15 mm slicer elephant-foot compensation; roller bottom chamfer 0.3 breaks any first-layer flare weld. Chamfers modeled only on circular edges; scalloped outline left to slicer compensation. Named parameter profiles shipped G-Man style: c_journal 0.20/0.25/0.30 × g_float 0.25/0.30/0.35. Variant ladder: OD 62 mini, 6/8-slot, three journal clearances, steel-ball HEAVY (one pause at z12.4, balls drop in open slots, no ceiling change needed since the window is open anyway), AMS slug palettes. MANDATORY FIRST PRINT — test coupon (Ghost Gauge graft): OD ~42 coupon containing the full journal pair + one slot + one roller, ~25 min; validates c_journal spin-free and g_float roller release before committing 3 h. Post-print QA on the flagship: one shake (all six slugs must rattle freely) and one flick (silence within a quarter-turn) — no break-in, no tuning.

### Why It Wins
Against the leaderboard formula it holds every table-stakes trait — one plate, zero hardware, 72 mm palm disc, filename-grade parametric clearances (now a 3×3 tune matrix), GIF-native cover, deep variant ladder — while claiming three confirmed whitespaces simultaneously: PiP audible/tactile feedback (currently hardware-only via Thor's Hammer), a mechanism outside the saturated gear/gyro duopoly (no corpus design has moving mass that changes radius; Wave Gyro's columns are decorative rattle, ours ARE the flywheel), and a credible path past the palm-size rim-ratio 1.2 ceiling (1.5 via the 30-second ball drop). Every judge deduction is directly answered: mid-spin ordinariness → the unoccluded seated band turns motion blur into a continuous drawn orange circle, so the spectacle now spans flick, full speed, and decay; occluding rails → crossbar relocated inboard (2.5 at r24), rails slimmed to 1.6, window widened to 5.8; roller-strand risk → anti-strand slicer protocol, parametric float gap, and a 25-minute coupon that converts the risk into a pre-flight check; bridging → all spans re-derived and capped at 8 mm. Against our six priors it delivers Governor-class fun (state changes you hear and feel) built exclusively from verified-robust geometry — free Ø8 cylinders at 0.5 mm clearances and the diamond journal at its exact proven scale — finally breaking the novelty-vs-printability inverse correlation the judges punished all season. Internal consistency errors in the judged draft (scallop formula vs count, sector-window wall violation) are fixed, so the spec is buildable as written with no interpretation.

### Risks
1) TEST PRINT REQUIRED — roller float release: g_float=0.30 behavior varies with cooling/material; the OD-42 coupon (journal + one slot + one roller) is a mandatory gate before the flagship; if the roller welds, step to 0.35. 2) TEST PRINT REQUIRED — seated silence and truth: race roundness at r33 after cooling shrinkage determines whether seated spin is truly silent; verify on flagship print #1, and confirm the death-rattle onset lands near the predicted 2.9 rev/s. 3) TEST PRINT REQUIRED — rail bridge quality: 7.75 mm outer rail segment over the open slot; slight first-layer sag is cosmetic (underside faces the slug cavity) but must not droop below z12.3 or it narrows the 0.5 roller top gap — measure on coupon-adjacent test or first flagship. 4) Conceptual adjacency to Governor (both centrifugal): mitigated by a different payoff (visual transformation + variable inertia vs click regulation) and zero fragile parts; listing copy must frame its own niche. 5) A stranded slug leaves ~5 g·mm imbalance — degraded, not disabled; caught by shake QA; anti-strand slicer settings reduce incidence. 6) Zero-hardware rim ratio ~1.25–1.3 will not out-coast the 61 g PiP Planetary on raw duration — the HEAVY ball variant owns the spin-time claim; lead the listing with the transformation. 7) Looks-broken-at-rest is a listing hazard — cover GIF must open on the transformation, and copy must name the death-rattle as the spin-down alarm feature. 8) HEAVY variant pause: verify slicer pause height lands exactly at z12.4 (layer 62 at 0.2 mm) and that balls seat below the ceiling before resuming — dry-run the pause once. 9) Fusion build: scalloped spline must never be chamfered (ASM_BL_CAP_COMPLEX); pattern features not bodies where possible; removeFeatures.add() for any cleanup.


---

# Analyst digests


## Mesh forensics
# Mesh forensics: MakerWorld top-30 spinner leaders

Method: scanline even-odd rasterization of z-slices (0.02–0.03 mm pitch) + connected-region labeling + EDT clearances, cross-checked with exact 3D body-to-body min-distance (KDTree-pruned point-to-triangle). All meshes PLA at 1.24 g/cm3. Uniform-disk reference for rim metric = 36% of volume beyond 0.8R.

## G-Man geometric/planetary family (print-in-place, all 14.2 mm tall)
Shared architecture: outer rotor with internal ring gear, fixed sun + hex hub stator, planet gears between. Three axial zones: involute-ish teeth z=0–3.5 and z=10.7–14.2 (3.5 mm each), smooth **non-circular cam band z=3.5–10.7 (7.2 mm)** that provides axial retention. Filename params are wall/clearances (e.g. "2.5 0.15 0.16", "0.12 2.6 0.13").
- **Geometric Core/Razor** (OD 84.8/82.3, 47.8/42.9 g): ring gear 72T internal (tip ID 67.3, root dia 76.0), sun 36T (tip OD 40.3, root ~35.3), 6 planets 18T (tip dia 21.9), center distance 27.2, module ≈1.0. Hub hex 24.1 across-corners/21.4 across-flats, finger bore dia 18.5, hub ring wall 2.8 mm (r9.25–12.05). **Gear flank clearance 0.12–0.15 mm; cam band kisses at lobes with 0.020 mm modeled gap** (rest of cam circumference: p5=0.68 mm, median 5.8 mm) — contact-point bearing that snaps free after printing. Secondary shell offsets 0.285 mm. Rim fraction ~32–36%.
- **Heavy Duty Blade** (OD 84.5, 39.4 g): sun 24T (tip dia 28.1) on knurled center button dia 20.0 (24 splines, 0.77–0.82 mm free ring around it), 6 fat planets 12T (tip dia 15.0), ring 48T internal (tip ID 50.5), CD 19.65, module ≈1.09. Cam band z2.5–11.7, cam clearance 0.058–0.061 mm; flank 0.09 mm. Decorative rim band r36.9–41.1 with 48 scallops. Rim 30.1%.
- **Planetary cog-10-large** (OD 87.8, 45.6 g, open center bore dia 33.2): stator sun-ring 40T (tip OD 43.3), 10 planets 15T (tip dia 17.5), ring 70T internal (tip ID 70.5), CD 28.46, module ≈1.035, teeth full 12 mm height but **crowned: flank gap 0.09 at ends tightening to 0.037–0.055 at mid-height**; 3D min planet↔races 0.057–0.061; planet↔planet 0.395. Rim 50.5%.
- **Square Fragment** (89.6 sq, 46.8 g): ring 72T, sun 24T (tip dia 30.1), 8 interlocking fragment-arms (~2.1 cm3 each, full height); frame clearances alternate 0.118–0.122 / 0.28 mm, cam lobes 0.018–0.021, adjacent fragments touch (0.000). Rim 50.4%.

## Print-in-Place Planetary Gear Spinner (OD 85, H 15, 61.3 g)
Textbook clean module 1.2 system: sun 18T solid disc (tip dia 24.0, root 18.56, whole depth 2.72=2.27m), 3 planets 18T, ring 54T internal (tip ID 62.4, root ID 67.9), CD 21.60. **Flank clearance 0.117–0.122 mm (3D exact)**. Teeth full height with ~3 mm chamfered entry at both faces. Ring body is an 11.3 mm-deep rim (r31.2–42.5) carrying ~59% of total mass; 50.7% of volume beyond 0.8R — the flywheel benchmark of the corpus. 30-scallop outer grip.

## Gyro Fidget Rings (flat 7-ring, OD 67, H 4.0, 14.1 g)
7 concentric rings + center disc (bore dia 15.9). **Radial pitch exactly 3.5 mm: ~2.95 mm wall + 0.15 mm gap** (3D gaps 0.150–0.153 across all 6 interfaces; 2D 0.126–0.136). Outer ring wider (4.0 mm wall). Ring outer radii 13.4/16.9/20.4/23.9/27.4/30.9/33.5. Pivot bosses make r-ranges overlap ~1.4 mm between neighbors. Rim 38.0%.

## Wave Gyro Heavy Duty (OD 90, H 14, 68.4 g)
Nested-ring gimbal core: 32-spike knob dia 19.9 → three rings ~2.8 mm radial width (r8.7–14.6, 12.6–18.2, 16.8–22.7) with **ring-to-ring clearance 0.375–0.380 mm**; wave cage pivots at 0.207–0.209 mm. 13 loose wave-profiled columns (dia 9.0 waisted to 7.0, full height) at orbit r27.5 with ~1.0 mm play — tactile rattle elements, not bearings. Heavy rim r35–45; 35.8% beyond 0.8R.

## FloW Arcspin (66×61.5, H 16.5, 38.5 g)
5 nested eccentric watertight arc bodies (3.1–8.4 cm3), all full height. In-plane arc-to-arc clearance 0.73–0.77 mm; bodies touch (0.000) at rail/pivot contacts in the assembly file. Smooth barrel z-profile (1500→1949→1500 mm2). Rim 29.6% — motion toy, not flywheel.

## Vega rings (two-part snap bearing rings, sizes 5–15, H 8.6)
Inner core: finger bore = US ring size (15.7 mm @5, 18.09 @8, +0.80 mm/size), wall ~1.8; outer spinning band wall ~2.3 (OD 22.5 @5 → 24.9 @8). Interlock (size 8): outer lip ID 20.37 vs core end OD 19.78 → **running clearance 0.30 mm radial**; core mid-ridge OD 21.63 vs lip ID → 0.63 mm/side snap interference; groove crest gap 0.50 radial. Pair mass 1.4–1.7 g.

## Copyable rules
Gear flank gaps 0.10–0.15; PIP bearing surfaces 0.15 (flat rings) to 0.38 (heavy gimbal); contact-lobe cams 0.02–0.06 only where surfaces meet at points; module 1.0–1.2, N_ring=N_sun+2N_planet everywhere; flywheels put ≥50% of volume beyond 0.8R via 11 mm-deep rims; 14–15 mm total height with 3.5 mm gear/retention zones.

**Key facts:**
- Gear flank clearances across all planetary leaders: 0.09-0.15 mm in-plane (G-Man 0.12-0.15, PiP Planetary 0.117-0.122 exact 3D, Blade/cog10 0.09)
- G-Man three-zone stack (14.2 mm total): gear teeth 0-3.5 mm and 10.7-14.2 mm, smooth non-circular cam retention band 3.5-10.7 mm (7.2 mm)
- G-Man cam bearing touches only at lobes: 0.020 mm modeled gap at contact points, p5=0.68 mm elsewhere - point-contact break-away bearing
- G-Man Core gear train: 72T internal ring (tip ID 67.3) / 36T sun (tip OD 40.3) / 6x 18T planets (tip dia 21.9), center distance 27.2 mm, module ~1.0
- PiP Planetary Gear Spinner: module 1.2, 54T ring / 3x 18T planets / 18T solid sun, CD 21.60 mm, tooth whole depth 2.72 mm, OD 85 x H 15 mm, 61.3 g
- Flywheel benchmark: PiP Planetary puts 50.7% of volume beyond 0.8R via an 11.3 mm-deep rim (r31.2-42.5) holding ~59% of mass; cog10 50.5%, Square Fragment 50.4% (uniform disk = 36%)
- Gyro Fidget Rings (7-ring, OD 67, H 4.0): radial pitch exactly 3.5 mm = ~2.95 mm wall + 0.15 mm gap; measured 3D ring-to-ring clearance 0.150-0.153 mm on all six interfaces
- Wave Gyro (OD 90, H 14, 68.4 g): nested gimbal rings ~2.8 mm radial width with 0.375-0.38 mm clearances, cage pivots 0.207 mm, plus 13 loose 9 mm wave columns at orbit r27.5 with ~1.0 mm rattle play
- G-Man cog-10-large teeth are crowned: flank gap 0.09 mm at faces tightening to 0.037-0.055 mm at mid-height; open-center design with bore dia 33.2 mm
- Vega two-part snap ring (size 8): running clearance 0.30 mm radial at lip (lip ID 20.37 vs core OD 19.78), snap interference 0.63 mm/side, bore steps 0.80 mm/US ring size, H 8.6 mm
- Arcspin: 5 nested eccentric arc bodies with 0.73-0.77 mm in-plane clearance, OD 66 x H 16.5, only 29.6% rim fraction - motion pattern toy, not flywheel
- Finger interface conventions: G-Man hub bore dia 18.5 with hex boss 21.4 AF, Blade knurled button dia 20.0 with 24 splines and 0.8 mm free ring, gyro center bore 15.9
- All leader spinners obey N_ring = N_sun + 2*N_planet (72=36+2x18, 48=24+2x12, 54=18+2x18, 70=40+2x15)
- Masses/sizes of leaders: G-Man family 39-48 g at OD 82-90 x 14.2; PiP 61.3 g; Wave Gyro 68.4 g; flat gyro 14.1 g; Vega pair 1.4-1.7 g
- Tooling note: dirty multi-shell STEP-exported STLs need scanline even-odd slice rasters at clean z + KDTree-pruned exact point-to-triangle 3D gaps; trimesh ProximityQuery times out without embree

## Popularity formula
# MakerWorld Fidget Spinner Success Formula and Whitespace

Sources: `C:\Users\gethi\source\fusionhelper\fidgetspinners\ANALYSIS.md` (top-30 leaderboard, likes+boosts, Aug 2026), `C:\Users\gethi\source\fusionhelper\fidgetspinners\scan_report.json` (139 STL/3MF parsed), `C:\Users\gethi\source\fusionhelper\docs\fidget-spinner-competitor-scan.md` (trimesh geometric scan + reconciliation).

## The success formula (all three sources agree)

**A flat, rim-weighted, rotationally symmetric print-in-place mechanism, 40-90 mm, that photographs as motion.** Decomposed:

1. **Print-in-place, zero hardware — the #1 trait.** Majority ship one STL that is the complete captive assembly; it spins straight off the plate. Only 1 of 30 (Thor's Hammer) needs hardware (5 mm bearing + MX keyswitch). The craft moat is tuned clearances: G-Man filenames encode gap values (`0.15 0.16 tighter`, `0.12 2.6 0.13`) so it spins freely on the first Bambu print.
2. **Palm flat disc.** ~20 of 30 are discs 40-90 mm dia, 4-21 mm thick, median max dim ~67 mm, 30-70 g at 100% PLA. Prints flat, no supports, 18 min-4 h.
3. **Two mechanisms own the chart:** planetary gear trains (9 models — counter-rotating gears in a ring, max visible motion) and nested concentric gyro rings (7 models — flat disc becomes sphere illusion when spun). Remainder: helix/vortex push-twist toys and novelty kinetic.
4. **GIF-legible motion.** Cogs, spikes, wave edges, AMS multicolour splits — every top cover image is a 2-second spinning GIF; the design must read as motion on the card grid.
5. **Variant breadth feeds the ranking flywheel.** Ring counts 4-8, Vega sizes 5-15, 9 textures, 6 gear variants, 10-22 community profiles each. More variants → more prints → leaderboard position.
6. **CAD-grade meshes.** STEP-derived exports, 250k-900k triangles on top discs; smooth involute flanks matter for spin feel and sound.
7. **Physics:** rim ratio (Iz / uniform disc) separates alive from dead. Gear/ring designs hit 1.0-1.2; pure Vega rings 1.65-1.71 (near-ideal rim weighting); sculpture/novelty at 0.45-0.7 "will feel dead" (Dahlia 0.45, Keychain 0.52, Shuriken 0.59).

## The gaps — what NO leaderboard design does

Confirmed by FFT symmetry analysis across the whole corpus:

- **Zero constant-width (Reuleaux-type) silhouettes.** Every disc is circular or square; only Arcspin is even 5-fold. A constant-width spinner rolls/spins as a non-circle — visually wrong in the best way, GIF-native, still perfectly balanced.
- **Zero asymmetric-but-balanced designs.** Nothing on the chart has an off-symmetry silhouette with a nulled CoM. Every top model is boringly rotationally symmetric; an asymmetric shape that spins true reads as impossible (the "Counterfeit Comet" concept).
- **No print-in-place haptic/audible feedback.** The only clicker (Thor's Hammer) needs a bearing and a keyswitch. A PiP ratchet/detent that clicks as it spins — sound and feel with zero hardware — is untouched territory between the silent PiP meta and hardware novelties.
- **No palm-size design that combines mechanism + extreme rim ratio.** The 1.65-1.7 rim ratios exist only in the tiny 22-31 mm Vega finger rings (0.5 g); the 85 mm gear discs max out ~1.2. A 60-90 mm PiP disc engineered past ~1.4 would out-spin the whole chart without hardware.
- **Saturated, avoid:** PiP planetary gears (4+ direct entries plus 5 G-Man siblings) and nested gyro rings (7 models) — cloning either is entering the most crowded lane. Classic tri-arm is the floor (11 g, rim ratio 0.77, thin) — the "boring clone" baseline.

## Positioning the whitespace

The gap between "spins off the plate" (table stakes) and "tri-arm clone" (worthless) is a design that keeps every formula element — one STL, no supports, palm disc, tuned clearances, GIF motion, variant ladder — while breaking exactly one expectation: silhouette (constant-width or asymmetric-balanced), feedback (PiP clicker), or physics (extreme rim ratio at palm size). The competitor scan's own reconciliation notes the repo's builds (Pentaroule 60, Counterfeit Comet) hold the silhouette whitespace but carry hardware friction (608 bearing + steel nuts, pause-insert); a bearingless printed-journal derivative (G-Man ~17 mm bore pattern) is the stated path to leaderboard viability while keeping the differentiating geometry.

**Key facts:**
- Top-30 MakerWorld leaderboard (likes+boosts, Aug 2026): 29 of 30 designs are zero-hardware; only Thor's Hammer needs a 5 mm bearing + MX keyswitch
- Success formula: flat, rim-weighted, rotationally symmetric print-in-place mechanism, 40-90 mm, that photographs as motion (GIF cover image)
- ~20 of 30 are palm flat discs 40-90 mm dia, 4-21 mm thick, median max dimension ~67 mm, 30-70 g at 100% PLA, print times 18 min-4 h
- Mechanism duopoly: planetary gear trains (9 models) + nested gyro rings (7 models) = 16 of 30; both lanes saturated
- G-Man filenames encode tuned print-in-place clearances (e.g. '0.15 0.16 tighter', '0.12 2.6 0.13') - first-print spin reliability is the craft moat
- Rim ratio (Iz vs uniform disc) predicts spin feel: gear/ring designs 1.0-1.2, pure Vega rings 1.65-1.71, sculpture/novelty 0.45-0.7 feels dead
- Top discs are STEP-derived CAD meshes at 250k-900k triangles (max: G-Man Core 908,030 tris)
- Variant breadth drives ranking: ring counts 4-8, Vega sizes 5-15, 9 textures, plus 10-22 community print profiles per model
- Whitespace 1: zero constant-width (Reuleaux) silhouettes in the entire corpus - only Arcspin is even 5-fold symmetric
- Whitespace 2: zero asymmetric-but-balanced (CoM-nulled) designs - every top model is rotationally symmetric
- Whitespace 3: no print-in-place clicker/ratchet - the only audible-feedback design requires hardware
- Whitespace 4: no palm-size (60-90 mm) design exceeds rim ratio ~1.2; the 1.65-1.7 ratios exist only in 22-31 mm finger rings
- Classic tri-arm baseline is the floor: 11 g, rim ratio 0.77, 5 mm thick - the 'boring clone' reference point
- Repo's own builds (Pentaroule 60, Counterfeit Comet) occupy the silhouette whitespace but carry hardware friction (608 bearing + steel nuts); a bearingless printed-journal (~17 mm bore) PiP derivative is the stated leaderboard path

## Theory + build learnings
# Flagship Fidget Spinner Design Rules (research + judge panel + verified Fusion builds)

## What the judges actually rewarded and punished
Scores split into three axes (fun, uniqueness, printability, /10 each). The winner (Pentaroule 60, 23.3/30) won on printability (8.7) despite mediocre fun (6.7); the best play concepts (Governor, fun 9; Vernier, fun 8) lost points because their headline feature rode on fragile geometry (0.3 mm detents, 0.5 mm PIP clearances, flexure pawls). Every judge summary states the same inverse correlation: novelty vs print reliability. The flagship must break that correlation — a mechanism-driven wow feature built ONLY from robust geometry. Also punished: smooth flick-starved silhouettes (dimple-only spin-up "a chore"), weight above ~90 g (96 g Reuleaux Seven "fatigues the hand"), one-trick payoffs (Comet "fades once the joke lands"), calibration-hostage tricks (100%-infill-dependent balance, 0.8 mm air gaps, BB trim sessions), and niche-splitting (two Reuleaux entries cannibalized each other). Rewarded: multiple honest play modes, audible/tactile state changes, illusions that work in steady daylight with zero electronics, and spectacle grounded in real optics/physics rather than reskin styling.

## Functional core (long true spin, hand feel)
1. **Rim-weight ruthlessly.** I = Σmr²; spin decays exponentially (ω = ω₀e^(−t/τ)), so inertia and bearing quality beat flick strength. Both world records are rings (rim I = mr² vs ½mr² disc). Put steel at ≥75% of max radius. Verified: hidden M8 nuts (pause-insert at z=8 mm, hex pocket AF 13.3 mm) triple inertia vs bare PLA.
2. **Corpus rim-ratio target 1.65–1.7** (verified from our builds): nested-ring class hits it and feels ideal; gear bodies at 1.0–1.2 are mediocre; novelty sculpture at 0.45–0.7 feels dead. This is the single number to check before committing geometry.
3. **Size/mass band:** 60–70 g total, 55–75 mm OD. Above 80 mm snags and reads desk-only; above 90 g fatigues.
4. **Bearing:** 608 (22×8×7), open, run dry (lube costs 30–70% spin time). Verified seat recipe: Ø21.85–21.90 mm PLA, 4+ perimeters, 0.5 mm lead-in chamfer, vise press, test ring FIRST. Caps bear on inner race only (Ø~11 boss, recess clears outer race), stems Ø8.1 mm.
5. **Flick cadence:** a graspable landmark every ≤90° (scallops, bulbs, corners at radius maxima). Do not ship a smooth convex rim with friction dimples only — judges called it flick-starved twice.

## Print-reliability floor (non-negotiable)
6. Flat-bottom pure 2D-profile extrusion, zero supports, all bridges ≤10 mm, chamfers at 45°. Sealed pockets close via G-code pause; ceilings land ~0.3 mm above steel so they're metal-supported, not true bridges.
7. **No sub-1.6 mm walls, no 0.3 mm detents, no printed flexures, no 0.2 mm tooth tips.** Every design punished by the print-engineer judge died on one of these.
8. **Chamfer only circular edges** (verified: chamfers on complex spline outlines fail with ASM_BL_CAP_COMPLEX in Fusion). Let slicer elephant-foot compensation handle the outline; keep modeled 0.3–0.5 mm chamfers on bore mouths and circular bottom edges.

## De-risked mechanisms (our verified recipes fix the judges' top objections)
9. **Print-in-place journal that works** (fixes Vernier's fuse-or-gritty risk): revolve a polyline — base radius 11 mm, 45° ridge 1.2 mm deep at mid-height, thirds of an 8–9 mm stack; female side = base + 0.25 mm radial clearance (PLA); 0.3 mm anti-fuse chamfers on BOTH bottom gap edges. Leaderboard designs tune 0.12–0.16 mm per printer variant — ship clearance as a parameter.
10. **Asymmetric-but-balanced without the fussy workflow** (fixes Comet's BB-trim dependency): drive a hidden void/mass position parameter, read CoM each recompute, **bisect** (overlap-proof) — converges in ~5 recomputes to <0.05 mm CoM offset. Newton on the analytic mass model oscillates; don't use it. Hidden sealed voids balance a no-hardware body; hidden steel balances a hardware body AND supplies inertia.

## Spectacle rules
11. Visual effect must be **speed-coupled and daylight-proof**: the moire spin-down "speedometer" (stator-mounted sampling grid over rotor pattern, registered by the bearing itself) was rated the most original idea in the field; spin-to-circle reveal (constant-width outline) and counter-rotating vernier beats also scored. Strobe-dependent layers are bonus only.
12. State changes people can hear/feel (clack, pitch shift, differential clutch) drove the highest fun scores — but implement via chunky sliding steel or the verified diamond journal, never via detents/flexures.
13. Claim ONE clear unclaimed niche (odd 5/7-fold symmetry, coaxial counter-rotation, asymmetric-balanced) and don't dilute it.

## Synthesis for the flagship
A ~65 g, ~70 mm flat-extrusion body with rim ratio ~1.65: pause-inserted M8 steel at ≥75% radius, verified 608 seat, scalloped flick landmarks every ≤72°, plus ONE mechanism-grade spectacle — counter-rotating ring on the verified 0.25 mm diamond journal or a stator-mounted moire reticle — with all clearances parametric and no feature under 1.2 mm.

**Key facts:**
- Judge scoring showed inverse correlation between novelty and printability; winner Pentaroule 60 took 23.3/30 on printability 8.7 with fun only 6.7 - the flagship must deliver a mechanism wow feature using only robust geometry
- Rim-weighting rules everything: I = mr^2 for a rim vs 0.5mr^2 for a disc; both world-record spinners (24:46 and 30:34) were rings; steel belongs at >=75% of max radius
- Verified corpus rim-ratio target: 1.65-1.7 (nested rings, ideal feel); gears 1.0-1.2 mediocre; novelty sculpture 0.45-0.7 feels dead
- Hand-feel band: 60-70 g total, 55-75 mm OD; judges punished 96 g (fatigue) and 84-88 mm (desk-only, snag)
- Verified 608 seat: Ø21.85-21.90 mm in PLA, 4+ perimeters, 0.5 mm lead-in chamfer, vise press, printed test ring first; bearing run open and dry (lubricant cuts spin 30-70%)
- Verified working print-in-place diamond journal: revolved polyline, base radius 11 mm, 45-deg ridge 1.2 mm deep at mid-height of an 8-9 mm stack, female = +0.25 mm radial clearance (PLA), 0.3 mm anti-fuse chamfers on both bottom gap edges; leaderboard tuning range 0.12-0.16 mm per printer
- Verified balance workflow for asymmetric bodies: drive hidden void/mass position parameter, measure CoM per recompute, bisect - converges ~5 recomputes to <0.05 mm; Newton oscillates; this replaces the Comet's fragile 100%-infill + BB-trim workflow
- Hidden pause-inserted M8 nuts (z=8 mm, hex pocket AF 13.3 mm) triple inertia; hidden sealed voids balance no-hardware bodies
- Fragile features that killed scores: 0.3 mm detents, 0.5 mm PIP clearances, 0.8 mm flexure pawls, 0.2 mm tooth tips, 1.7-1.9 mm webs, 0.85 mm walls - floor is 1.6 mm walls and nothing sub-1.2 mm
- Verified Fusion gotcha: chamfers on complex spline outlines fail (ASM_BL_CAP_COMPLEX) - chamfer circular edges only, let slicer compensation handle elephant foot on the outline
- Flick-starved smooth silhouettes were punished twice; provide a flick landmark (scallop/bulb/corner at radius maxima) every <=90 degrees
- Spin decays exponentially (omega = omega0*e^(-t/tau), one spinner halved every ~40 s), so doubling flick speed adds only ~1 time constant - design for inertia and dry bearing, not flick strength
- Highest-rated spectacle ideas: stator-mounted moire reticle as live spin-decay speedometer (most original in field), spin-to-circle constant-width reveal, counter-rotating vernier beat (36 vs 30 slots); audible/tactile state changes drove the top fun scores (Governor fun 9)
- Print plan invariants: flat-bottom 2D-profile extrusion, zero supports, bridges <=10 mm, pocket ceilings land ~0.3 mm above inserted steel, 0.2 mm layers, deterministic infill (100% or perimeter-dominant) to preserve balance
- Claim exactly one unclaimed niche; the two Reuleaux entries split one niche and both lost points for it

---

# All four candidates


## [0] Pulsar Bloom 78 (MAXIMUM MOTION)

**Concept:** A zero-hardware print-in-place spinner whose gears are completely hidden: flick the deep fluted rim and four bright pucks trace a 4-lobed hypotrochoid fixed in your hand's frame, always forming a perfect square that rhythmically blooms out to the rim and collapses inward — 4 pulses per revolution. At flick speed the pucks blur into a glowing 4-petal rosette; as the spin decays the breathing square emerges in slow motion, making the spinner its own live speedometer. It is the leaderboard planetary DNA (module 1.0, proven flank clearances, one STL) with the cogs invisible and the kinematics turned into choreography.

**Pizazz:** The 2-second GIF: a spinning disc with no visible mechanism, and four dots that are NOT rotating with it — they shuttle in and out along paths fixed relative to your fingers, snapping into an expanding-contracting square. It reads as impossible because the eye expects everything on a spinner to rotate; instead the pattern breathes in place while the disc whirls under it. Speed-coupled and daylight-proof (judges' top-rated spectacle class): fast flick = shimmering rosette blur, mid speed = hypnotic pulsing, dying spin = slow-motion bloom you can watch land. In hand: 12-flute deep rim gives a flick landmark every 30 degrees, the 4-planet mesh adds a soft turbine whirr, and a single filament swap at z=10.8 makes pucks + arms + center cap pop in an accent color with no AMS required. Cusp moments — where each puck momentarily freezes at max radius while the disc spins — are never occluded (3.05 mm verified clearance to the arms), so the money shot is always visible.

**Geometry:** Envelope OD 78.0 x H 14.5 mm, all-PLA, one STL, three body groups. GEARS: module 1.0, 20-deg involute, internal ring 56T (pitch Ø56.0, tip ID Ø54.0, root Ø58.8, teeth z2.4-10.3, 0.5x45 entry chamfers, smooth counterbore Ø58.8 z10.3-11.0), 4 planets 14T (tip Ø16.0, root Ø11.5, z4.6-10.6, +0.3 profile shift to kill undercut), centers r21.0 at 0/90/180/270; rolling condition 28-7=21 satisfied; 56/4=14 teeth per station (integer) so all planets are identical bodies at identical mesh phase. Flank backlash 0.12 mm modeled (parametric; 0.10/0.14 variants). STATOR: base disc r0-32.9 x z0-2.0 with Ø20x0.8 underside pinch dimple; ring-gear wall r_root 29.4 to r33.0 (wall outer face 32.8... solid band 29.4-32.8), z2.0-11.0; center post Ø16.0 z2.0-10.9 = verified diamond journal profile (45-deg ridge 1.2 mm deep, ridge band z5.4-7.8, 0.3 mm anti-fuse chamfers both bottom gap edges), stepping to Ø12 stem z10.9-13.0 and Ø18 cap head z13.0-14.5 with top pinch dimple (head overlaps hub bore 0.75/side = finger shield + redundant retention). ROTOR (one connected body): skirt r33.4-39.0 x z0-13.3 printing directly on bed, 12 outer flutes R1.5 at 30-deg pitch; 4 arms z11.3-13.3, 8 wide, at 45-deg offset stations, spanning skirt inner face to riser tops (bridge 6.9 mm over 0.3 gap on wall top at r32.8); 4 riser slabs 4 wide x r22.5-26.5, z4.3-11.3 (between planet stations — geometrically can never meet planets or pucks, min clearance 4.0 mm); carrier plate annulus r11.05-26.7 x z2.3-4.3; hub sleeve bore = post +0.25 mm radial (female diamond), OD r11.05, z2.3-10.9 (8.6 mm journal stack per verified recipe); 4 axle stubs at r21.0: mini diamond journals, Ø5.2 base with 45-deg ridge to Ø6.8 at mid-height, z4.3-10.3. PLANETS: blind center bore Ø5.8 with matching diamond groove Ø7.4 (0.30 radial clearance), 2.05 mm root wall at groove, solid cap z10.4-10.6 bridging the stub top; puck Ø5.0 x z10.6-13.5 (2.9 tall) at k=5.3 from planet center, assembled pointing radially outward on all four. Clearances elsewhere: all vertical PiP gaps 0.30; skirt-to-wall radial 0.6 (free, non-bearing); bed-level radial gap base/skirt 0.5; puck swing envelope r11.7-28.8 verified against hub (1.95), teeth (0.6 via z10.3 tooth stop), arms (3.05).

**Mass Distribution:** Single center bearing (verified Ø16-scaled diamond journal) so all running friction is at small radius; the skirt floats at 0.6 mm and touches nothing. Rotor ~36 g of ~57 g total: skirt alone is ~21 g at mean r36.2 in a 13.3 mm-deep rim band r33.4-39.0 — echoing and exceeding the PiP Planetary benchmark's 11.3 mm rim — putting ~59% of rotor volume beyond 0.8R (uniform disk = 36%). Rotor rim ratio ~1.25-1.3 vs uniform disc, above the 1.2 palm-size ceiling of the entire leaderboard, plus 4x ~1.2 g planets orbiting at r21 adding mr^2. Balance is exact by construction: 4-fold symmetric carrier, identical planets, and the four synchronized pucks' offset vectors sum to zero at every rotor angle (90-deg spacing rotated equally), so no counterweights, voids, or trim workflow are needed — first print spins true at any infill.

**Print Plan:** One STL, flat on bed, zero supports, 0.2 mm layers, 0.4 nozzle, 4+ perimeters, PLA, ~3 h. Both stator base and rotor skirt print from z0 with a 0.5 mm bed-level radial gap (anti-elephant-foot fusing) plus 0.3 mm chamfers on all bottom gap edges. PiP gaps: 0.30 vertical everywhere (plate over base, planets over plate, arm undersides over wall top, stub-cap ceilings); radial 0.25 center journal, 0.30 stub journals, 0.12 gear flanks. Longest bridge 6.9 mm (arm riser-to-skirt); stub caps bridge Ø5.8 over 0.3; all other spans supported — under the 10 mm rule with margin. Min feature: Ø5.0 pucks, 1.95 mm walls, nothing below 1.6 mm structural / 1.2 mm feature floor; no flexures, no detents. Optional single manual filament swap at z=10.8 colors pucks, arms, and cap head as one deliberate accent layer (no AMS needed). Ship clearance as parameters: flank 0.10/0.12/0.14 and stub 0.25/0.30/0.35 printer variants, G-Man style. Fusion build notes: use removeFeatures.add() not BRepBody.deleteMe() for any body cleanup in the parametric script; chamfer only circular edges (ASM_BL_CAP_COMPLEX gotcha); circular-pattern the planet+stub+riser+arm group (14-tooth station pitch guarantees identical mesh phase).

**Why It Wins:** Against the leaderboard formula it checks every table-stakes box — one STL, zero hardware, palm flat disc 78x14.5, tuned parametric clearances encoded as variants, deep-rim flywheel, GIF-native cover — while claiming motion whitespace nobody on the chart touches: all 9 planetary entries show plain meshing cogs and all 7 gyro entries show nested rings; none makes the kinematics draw a pattern, and the corpus has zero choreographed/animated designs. It simultaneously nudges past whitespace #4 (rotor rim ratio ~1.25-1.3 vs the 1.2 palm-size ceiling). Against our six priors: unlike Pentaroule and Comet it needs no bearing, nuts, or pause-inserts (the exact friction the competitor scan flagged as the leaderboard blocker); unlike Vernier Contra-Ring the visible effect is not counter-rotation beats but a non-rotating breathing figure; unlike Governor it has no fragile detent/pawl geometry — the wow feature is built entirely from corpus-proven robust elements (module-1.0 gears at 0.12 backlash, the verified diamond journal at two scales, 0.3 PiP gaps), directly breaking the novelty-vs-printability inverse correlation the judges punished. Variant ladder is built in: backlash/journal tunes, a 3-lobe deltoid sibling (ring 42T/3 planets 14T, 120-deg stations = 14 teeth, integer), and accent-color swap heights.

**Risks:** (1) 14T planets risk involute undercut — mitigated with +0.3 profile shift (12T precedent exists in the corpus Blade); verify mesh in Fusion before export. (2) Mini diamond stubs (Ø5.2/ridge Ø6.8) are a new scale for the verified journal recipe — 0.30 clearance chosen above the 0.25 center value; fallback variant with Ø6.5 stubs and 0.35 clearance if first print binds; worst case a fused stub frees with a firm planet twist (break-away like G-Man cam lobes). (3) Four gear meshes + five journals cost spin time vs plain-bearing spinners — positioned honestly as the motion flagship (Arcspin precedent: motion toy, 29.6% rim, still top-30), and the 21 g skirt keeps decay slow enough for the full fast-blur-to-slow-bloom arc. (4) Arm bridges land on 0.3 gaps over wall and stub tops — first layer of each bridge sags slightly; cosmetic only, hidden underside. (5) Rotor rim ratio ~1.3 undercuts the 1.65 nested-ring ideal — accepted trade for the mechanism; the brief is MAXIMUM MOTION, and no high-rim design can host it. (6) Puck-arm clearance margins (3.05 mm) assume exact assembly phase — the integer 14-tooth station pitch enforces it in CAD, but the build script must place planet rotation angle explicitly, not rely on visual alignment.


## [1] Supernova (ILLUSION + PHYSICS)

**Concept:** A print-in-place spinner that appears broken at rest: six loose contrast-color slugs rattle visibly in open radial slots, slumped at random positions. One flick and every slug leaps outward within a quarter-turn, snapping into a perfect wider ring against a hidden race - the rattle goes dead silent and it spins glass-smooth for minutes. It is the corpus's first variable-inertia spinner: the flywheel assembles itself at speed, and disassembles audibly as the spin dies.

**Pizazz:** The 2-second GIF: top-down, black body, signal-orange slugs scattered at random radii - flick - the orange dots explode outward in sync, the visible ring diameter grows 40% (40 mm to 58 mm), and locks into perfect symmetry. Expectation is weaponized twice: in the hand it feels like a failed print (shake it, it clatters like loose debris), then spins truer and longer than anything that feels solid; and on spin-down it counts itself out - below ~3 rev/s centrifugal force loses to gravity and the slugs begin cascading, an audible built-in spin-decay alarm ending in the death-rattle. Rattle-to-silence-to-rattle is a full sensory lifecycle with zero hardware, hitting the untouched PiP-audible-feedback whitespace. AMS two-color split (slugs as separate bodies on one plate) makes the transformation camera-legible.

**Geometry:** Envelope OD 72.0 x H 14.0 mm, flat bottom, 6-fold symmetric, three body classes in one plate. STATOR HUB: bottom cap Ø26 x 2.5 (z0-2.5); journal column per verified recipe - base radius 11.0, z2.5-11.5, 45-deg diamond ridge 1.2 deep (peak r12.2) centered z7.0 (span z5.8-8.2); top cap Ø26 z11.5-14.0; spherical finger dimples Ø18 x 1.2 deep both cap faces; 0.4 chamfers on cap circular rims; 0.3 anti-fuse chamfers on both bottom gap edges. ROTOR: female journal = male + 0.25 radial (bore r11.25, groove peak r12.45; parametric, ship 0.20/0.25/0.30 variants); cap counterbores r13.4 x 2.8 deep both ends (0.4 radial / 0.3 axial cap clearance); sleeve to r16.0; deck r16-33 full height with 6 roller slots at 60 deg - width 9.0, radial span r16 to r33 (race = rim inner cylinder at r33, concentric), floor top z1.2, ceiling z12.4; top viewing window 5.4 wide (two rails 1.8 wide x 1.6 thick + one 2.0 crossbar at mid-length, max bridge ~7 mm); floor solid (no bottom window); 6 full-height sector lightening windows between slots (r18-30, ~28 deg, >=2.5 mm walls, no chamfers on complex edges); RIM r33-36 full height, outer silhouette R(theta)=35.4+0.6cos(6theta) with 12 scallops 1.5 deep (flick landmark every 30 deg). ROLLERS x6: Ø8.0 x 10.4 cylinders, 0.3 chamfers both circular ends, printed at rest position (axis r20.5), bottom gap 0.30 above floor, 0.5/side tangential, 0.5 top; radial travel 20.5 to 29.0, seating as a line contact on the r33 race. All clearances >=0.25, all walls >=1.6, no flexures, no detents.

**Mass Distribution:** ~51 g PLA at 100%/perimeter-dominant infill. Rim ring (r33-36 x H14) ~11.3 g at r_avg 34.5; deck lightened by 6 slots + 6 through-windows to push volume outward; rollers 4.3 g seated at r29 during spin. Zero-hardware rim ratio ~1.2 at rest rising to ~1.25-1.3 seated (>=40% volume beyond 0.8R vs 36% uniform) - and the headline physics is that inertia is HIGHER spinning than at rest. Balance is by construction: 6-fold symmetry, identical rollers, single concentric race radius - no bisection, no trim, no calibration hostage. HEAVY variant: filament-change pause at z12.4 (before rails close), drop six Ø8 chrome bearing balls (2.05 g each) replacing printed rollers - +12.3 g all at r29 lifts rotor inertia ~30% to rim ratio ~1.5, beating every palm-size leaderboard design while staying a 30-second, sub-1-GBP insert with no glue or press-fit.

**Print Plan:** Single plate, flat-bottom 2D-profile extrusions, zero supports, 0.2 mm layers, 4+ perimeters, stock 0.4 nozzle PLA. Hub cap, rotor, and rollers all rise from z0 region; rollers print standing on a 0.30 mm horizontal separation gap over the solid slot floor (standard PiP planet-gear practice). All bridges <=7 mm (rail spans split by crossbar; cap ring bridges 2 mm over 0.3 gaps). Chamfers only on circular edges (bore mouths, cap rims, roller ends) - scalloped outline left to slicer elephant-foot compensation. Journal clearance shipped as a named parameter with 0.20/0.25/0.30 profiles, G-Man style. Variant ladder: OD 62 mini, 6/8-pocket, three journal clearances, steel-ball HEAVY (one pause at z12.4), AMS two-color slug palettes. Post-print QA: one shake (slugs must rattle freely) and one flick - no break-in, no tuning.

**Why It Wins:** Against the leaderboard formula it keeps every table-stakes trait - one plate, zero hardware, palm disc 72 mm, tuned parametric clearances, GIF-native motion, variant breadth - while claiming three confirmed whitespaces at once: PiP audible/tactile feedback (currently hardware-only via Thor's Hammer), a mechanism outside the saturated gear/gyro duopoly, and a credible path past rim ratio 1.2 at palm size (1.5 with a 30-second ball drop). No corpus design has moving mass that changes radius; Wave Gyro's loose columns are decorative rattle, ours are the flywheel. Against our six prior builds: no constant-width silhouette (Pentaroule), no asymmetric-balance/hidden voids (Comet), no counter-rotation (Vernier), no clicking regulation (Governor) - and it directly answers the judges' core demand by delivering a Governor-class fun score (state change you hear and feel) built exclusively from robust geometry: free 8 mm cylinders, 0.5 mm clearances, the verified 0.25 mm diamond journal. It breaks the novelty-vs-printability correlation instead of riding it.

**Risks:** 1) Conceptual adjacency to Governor (both use centrifugal mass) - mitigated by a different payoff (visual transformation + variable inertia vs click regulation) and zero fragile parts; must be framed as its own niche in listing copy. 2) A slug stuck by stringing or first-layer flare fails to seat, leaving ~5 g*mm imbalance - mitigated by 0.5 mm side clearances, 0.3 chamfers, smooth floor, and the shake-test QA; worst case is perceptible but not disabling. 3) Zero-hardware rim ratio ~1.25 will not out-coast the PiP Planetary's 61 g on raw numbers - the steel-ball variant covers the spin-time crown; listing should lead with the transformation, not endurance. 4) Roller print quality on a 0.30 mm float gap varies by cooling/material - ship the gap as a parameter alongside journal clearance. 5) Death-rattle may read as defect to uninformed buyers - the cover GIF and copy must sell it as the spin-down alarm feature. 6) Fusion build note: scalloped outer spline must not be chamfered (ASM_BL_CAP_COMPLEX); model chamfers only on circular edges.


## [2] Cicada 75 — the spinner that talks back (TACTILE FLAGSHIP)

**Concept:** A two-body, zero-hardware print-in-place spinner on the verified diamond journal, with one deliberate degree of freedom added: the rotor floats 1.6 mm axially on the journal. One thrust interface is a 28-tooth radial corrugation ring, the other is the journal's own smooth 45-degree cone. Tilt selects the interface: hold the spin plane vertical and it glides silently on the ridge; tilt the ribbed cap downward and the rotor's weight progressively loads the tooth ring, producing a pitch-coupled growl that doubles as an audible speedometer and an analog brake. It is the first print-in-place spinner with sound and tactile state changes, built entirely from chunky solid-face geometry.

**Pizazz:** The 2-second GIF: a silently spinning open-ring flywheel is tilted flat and instantly ROARS — a 200+ Hz brap whose pitch glissandos down as it brakes to a stop, then tilts back up and goes silent again. Sound + motion in one gesture, daylight-proof, zero electronics. In hand it is four toys: (1) silent marathon glide with 1.55 rim ratio inertia you feel resist your wrist; (2) tilt-throttle — growl volume and drag are analog with tilt angle, and every tooth impact is felt as a tick in the pinch because the stator hub carries the reaction; (3) wrist-pump blips — sharp axial jerks while spinning make it bark; (4) at rest it is a deep 40 g castanet — shake along the axis and the rotor clacks between its 1.6 mm stops. Click rate = 28 x rev/s, so the spin-down is literally audible: buzz, to purr, to discrete ticks, to stop. The reach-for-it-again factor is the conversation between hand orientation and sound.

**Geometry:** All parametric, mm, axisymmetric, two bodies + PiP. Envelope OD 75.0 x H 14.0. STATOR HUB: core cylinder r0-11, z0-14; male diamond journal per verified recipe — base radius 11.0, 45-deg ridge 1.2 deep (peak r12.2), ridge axial extent 3.0 centered z7.0, journal band z2.5-11.5; top cap disc r0-15.5, z12.2-14.0 (solid >=1.2 thick at thinnest), cap underside carries 28 radial wedge teeth pointing down over annulus r12.5-15.3: depth 0.6, 45-deg flanks, circumferential pitch 3.0 at r13.9, tip land >=1.2 (coin-reeding on a solid face, not a flexure); pinch pads = cap top face (spherical dimple dia 14 x 1.0 + 24 reeded flutes on the circular edge, 0.5 chamfer) and hub bottom face dia 22 (dimple dia 12 x 0.8). ROTOR: female journal sleeve inner r11.25 (base + 0.25 radial clearance, parametric 0.20-0.30), internal groove to r12.45, groove height 4.6 = ridge 3.0 + FLOAT 1.6, groove bottom face 0.2 above ridge bottom with 0.3 anti-fuse chamfers on both bottom gap edges (verified recipe); sleeve wall r11.25-14.05 (1.6 wall), z0-10.6; tooth ring flange on sleeve top r12.5-15.3, root plane z10.9, teeth pointing UP depth 0.6 (tips z11.5), 45-deg underside chamfer on the 1.25 flange overhang; print-state tip-to-tip gap to cap teeth = 0.7, so mesh begins at 0.7 rise, flanks carry from 0.7-1.3, hard stops (sleeve-top vs cap plane, ridge vs groove top) at 1.6 — tips never bottom out. 4 spokes: rectangular 3.0 wide x 3.0 tall, z0-3.0, spanning r14.05-30.5, at 90 degrees. Rim: r30.5-37.5, z0-14 full height; outer silhouette 24-lobe sinusoid, amplitude +/-1.2 about r36.3 (crests at 37.5); inner rim edge circular, 0.5 chamfer; NO chamfer on the scalloped outline (ASM_BL_CAP_COMPLEX gotcha — slicer elephant-foot comp handles it). Mode physics: spin plane vertical = radial load on ridge, faces free, silent; ribbed-cap-down tilt = rotor weight loads tooth pair, growl/brake; ribbed-cap-up tilt = ridge cone thrust, quiet hiss. Fusion build: revolved polylines for both journal profiles, circular-pattern wedge cuts for teeth (28x) and scallops (24x), extruded spokes; chamfer circular edges only.

**Mass Distribution:** PLA 1.24 g/cm3, 100% infill. Rotor: rim ring 20.9 cm3 = 26 g at r_rms^2 = 11.7 cm2 giving I = 304 g.cm2; slim sleeve + tooth ring ~2.3 g, spokes ~0.7 g; rotor total ~29 g, I = 312 g.cm2. Rim ratio = I / (0.5 m R^2) = 312/202 = 1.55 — above every palm-size leaderboard design (gear discs max ~1.2) and inside the verified ideal band 1.65-1.7's approach; ~90% of rotor volume beyond 0.8R (rim starts at 30.5 = 0.81R). Hub ~8 g; total ~38 g — G-Man family territory (39-48 g), pocketable, no fatigue. Balance is free: every feature is 4/24/28-fold rotationally symmetric, deterministic 100% infill, no CoM nulling needed. Growl-mode drag is the feature (tooth-climb energy ~5-7 mJ/rev at full flat = decisive brake; tilt angle meters it analog); silent-mode drag is the verified journal's line contact only. Variant ladder for the MakerWorld flywheel: tooth counts 20/28/36 (voice pitch), clearance 0.20/0.25/0.30, OD 65/75, plus a minimal-hardware "Baritone" variant with six rim bulb pods (dia 15) taking pause-inserted M8 nuts at r>=32 (>=85% R) for ~60 g and ~3x inertia — hardware that demonstrably earns its cost, sold beside the zero-hardware default.

**Print Plan:** One 3MF, two bodies, printed assembled, flat on plate, zero supports, 0.2 mm layers, 4 perimeters, 100% infill, PLA, ~2.5-3 h on a stock 0.4 mm Bambu/Prusa. Hub core, rotor sleeve, spokes, and rim all sit on the plate (flat-bottom 2D-profile extrusions). PiP interfaces: 0.25 mm radial journal clearance shipped as a named parameter (0.20/0.25/0.30 profiles, mirroring the G-Man tuned-clearance moat); 0.3 mm anti-fuse chamfers on both bottom gap edges at z0 per the verified recipe. Ridge overhang is 45 degrees — self-supporting. Cap underside (z12.2) bridges the 3.2 mm radial gap over the rotor tooth ring with a 0.7 mm axial gap — span well under the 10 mm bridge limit; downward teeth are +/-45-deg zigzag walls, printable, and first-layer roughness self-burnishes in the first minute of growl use. No pause, no inserts, no supports in the default SKU; the Baritone variant adds one G-code pause at z=8 with pocket ceilings 0.3 mm above the nuts (metal-supported, verified recipe). Spins and clacks straight off the plate — the break-free test is one axial shake.

**Why It Wins:** Against the leaderboard formula: keeps every table-stakes element (one file, zero hardware, no supports, palm disc, tuned parametric clearances, variant ladder, GIF-native motion) while claiming the one whitespace nobody holds — print-in-place audible/tactile feedback (the only clicker on the chart needs a bearing and a keyswitch) — and stacking the second whitespace on top: rim ratio 1.55 at 75 mm where no palm design exceeds ~1.2. It avoids both saturated lanes (no planetary gears, no nested gyro rings) and its cover GIF has a sound story, which nothing in the corpus has. Against our six builds: Pentaroule/Comet were silhouette plays with hardware friction — this is zero-hardware; Vernier and Governor had the best fun scores but died on 0.5 mm PiP clearances and flexure pawls — Cicada delivers Governor-class audible fun using only a verified journal, solid-face corrugations with 45-deg flanks and >=1.2 mm lands, and gravity as the spring. It directly breaks the novelty-vs-printability inverse correlation the judges identified: the wow mechanism IS the robust geometry. Multiple honest play modes (silent glide, tilt growl, wrist blips, castanet) answer the one-trick criticism of the Comet.

**Risks:** 1) Growl drag magnitude is analytic, not yet printed: 0.6 mm tooth depth may brake harder or softer than ideal — depth is a single parameter (0.3-0.8 sweep on one test print); the design intent already frames growl mode as a brake/speedometer, silent mode as the marathon. 2) Cap-underside teeth print as short bridges — first-print tips will be rough; mitigated by 0.7 mm print gap, 45-deg flanks, >=1.2 mm lands, and self-burnishing; worst case is a softer voice, not a failure. 3) Accidental grazing in silent mode if the user holds it slightly tilted — float 1.6 mm and 0.7 mm neutral gap make contact require deliberate tilt; residual light tick is arguably a feature (orientation feedback). 4) 38 g default is lighter than the 60-70 g ideal band — inertia (I=312 g.cm2) is mid-pack G-Man territory, and the Baritone nut variant covers heft-lovers; do not chase mass with a solid disc (kills the 1.55 ratio). 5) Axial-clack mode could read as looseness to some users — listing copy must frame the 1.6 mm float as the mode mechanism. 6) Sound level in growl mode is unmodeled (PLA ring resonance) — claim 'purr/growl', not decibels, until the prototype is recorded.


## [3] Ghost Gauge 75 — the print-in-place spinner with a built-in moiré speedometer (WILDCARD)

**Concept:** A zero-hardware, print-in-place flywheel spinner (OD 75 x H 14.4 mm, ~45 g) whose stationary hub carries a flat sampling reticle under a spoked rotor grating: the two gratings form a live moiré "gauge" that shimmers at full speed, then condenses into four ghost blooms that orbit at 9x rotor speed as the spin decays — a speedometer you watch to the last degree. It marries the two biggest unclaimed niches in the data (no palm-size design above rim ratio ~1.2; the judges' highest-rated spectacle, the stator-mounted moiré reticle, which no leaderboard design ships) using only verified-robust geometry: the proven 45-degree diamond journal, no feature under 1.6 mm, no bridge over 9.6 mm.

**Pizazz:** The 2-second GIF: flick it and the annular window between hub and rim scintillates like heat-haze; as speed falls, four dark blooms materialize out of the shimmer and sweep like helicopter blades (9x angular amplification, rotor 36 spokes vs stator 40 apertures), finally creeping like a second hand in the dying seconds — the spin-down, normally the boring part, becomes the show, and viewers watch to full stop. It is strobe-free, daylight-proof, and works in silhouette (transmissive moiré when held to light). In hand: deep turbine-style rim gives a gyroscopic heft no gear spinner matches, 12 scallops give a flick landmark every 30 degrees, and the diamond journal has the G-Man-style clean dry hiss. One filament-change pause at layer 7 (z=1.4 mm) makes the stator reticle a contrasting color seen through the rotor grating — a two-tone moiré from a single-nozzle printer. Variant ladder is built in: bloom count (4-bloom standard, 39/40 single-sweep "second hand" at 39x amplification), journal clearance 0.15/0.20/0.25, OD 65/75, mono vs two-tone.

**Geometry:** One STL, two bodies, all z from plate, total H 14.4 mm (72 x 0.2 mm layers), OD 75.0. STATOR (pinched, stationary): finger bore dia 18.5 through, z0-14.4; hub annulus r9.25-12.0 full height (wall 2.75, G-Man convention); integral hex boss 20.8 AF z11.4-14.4; 0.5 x 45-deg chamfers on bore mouths (circular edges only per Fusion ASM_BL_CAP_COMPLEX rule). Male diamond journal on hub OD: revolved polyline, base radius 12.0, 45-deg ridge 1.2 mm deep (peak r13.2) centered z6.5, axial extent z5.3-7.7. Reticle flange z0-1.2, r12.0-24.3, printed flat on plate, 40 radial apertures leaving 40 bars of constant 1.6 mm width (~50% duty at r20). ROTOR: rim r29.0-37.5, z0-14.4, from plate, 12 cosine scallops 1.5 mm deep on OD; web ring r24.8-29.0, z0-4.2, from plate; spoke grating of 36 radial spokes, 1.8 mm wide x 2.4 mm thick, r15.2-24.8, z1.8-4.2 — each a 9.6 mm bridge anchored both ends (collar and web ring), spanning 0.6 mm above the reticle flange top (z1.2 vs z1.8); collar r(12.0+c)-15.2, z1.8-11.0, grown upward from the spoke ends, carrying the female diamond groove (base radius 12.0+c, 1.2 mm deep, 45-deg flanks, 0.3 mm anti-fuse chamfers on both bottom gap edges per verified recipe). Clearances: journal radial c = 0.20 default (parametric, 0.15/0.20/0.25 ladder mirroring G-Man filename-encoded tuning); vertical flange-to-spoke and flange-to-collar gaps 0.6; radial flange-OD-to-web-ring 0.5; hub-to-collar radial = c. Moiré counts share gcd 4 -> 4 symmetric blooms, amplification = 36/|40-36| = 9x. Fusion build: 2D sketches + extrudes + one revolve (journal) + circular patterns (36, 40, 12); all counts, widths, c, rim ID, web height exposed as user parameters.

**Mass Distribution:** Everything is rotationally symmetric (36/12-fold rotor), so CoM is nulled by construction — no balance workflow needed. Inertia strategy: the rotor is a chimney rim (r29-37.5, full 14.4 mm height, ~24 cm3) with only a 2.4 mm spoked web and a minimal journal collar inboard; estimated rotor Iz ~= 4.0e4 g*mm2 at ~40 g, rim ratio Iz/(0.5*m*R^2) ~= 1.40-1.42 as drawn, with ~58% of rotor volume beyond 0.8R (corpus flywheel benchmark: 50.7%; best palm-size leaderboard ratio ~1.2). Tuning loop: expose web-ring height and rim inner radius as parameters, read Fusion mass properties each recompute, and bisect toward ratio >= 1.45 (the verified bisection-on-recompute workflow, ~5 iterations). Stator ~5 g does not rotate. Total ~45 g — inside the 39-68 g leaderboard band; the hex-AF hub and 18.5 mm bore follow the proven G-Man finger interface.

**Print Plan:** PLA, flat on plate, zero supports, 0.2 mm layers, 4+ perimeters, deterministic perimeter-dominant/100% infill below z4.2 for the thin sections. Print stack: z0-1.2 stator flange + hub + rotor rim + web ring all on plate; z1.8 rotor spokes bridge 9.6 mm (under the 10 mm limit) anchored at both ends over the 0.6 mm gap; collar grows upward off the spoke ends to z11.0; hub/hex tops out at 14.4. No pause-inserts required; one OPTIONAL filament change at z1.4 for the two-tone moiré. No feature below 1.6 mm, no detents, no flexures, no tooth tips — the entire mechanism is the verified diamond journal (base r12, 1.2 mm ridge, +0.20 mm radial, anti-fuse chamfers), which snaps free like the G-Man cam band. Ship a 20-minute OD-40 core coupon (journal + collar + spokes + flange only) as a test print, same file philosophy as the verified 608-seat test ring. Estimated full print ~3 h.

**Why It Wins:** It satisfies every term of the leaderboard formula the analyses agree on — one STL, zero hardware, spins off the plate, flat palm disc at the 75 mm sweet spot, filename-grade tuned clearances shipped as parameters, and a variant ladder (clearance x bloom count x size x color) to feed the ranking flywheel — while avoiding both saturated lanes (planetary gears: 9+ entries; gyro rings: 7). It claims the whitespace nothing on the chart touches: a readable, physics-native spectacle (the moiré reticle was rated the most original idea the judge panel saw) fused with the highest rim ratio of any palm-size PiP design (~1.4 vs the chart's ~1.2 ceiling), and the moiré is arguably the most GIF-native cover image possible because the effect literally is an animation. Against our six builds it is markedly different: circular silhouette (not Pentaroule/Reuleaux), symmetric (not Comet), stator-grounded sampling registered by its own bearing rather than counter-rotating slots (not Vernier Contra-Ring), no speed-limiting mechanism (not Governor), and it finally breaks the novelty-vs-printability inverse correlation the judges kept punishing: the wow feature is made entirely of flat plates, 1.6-1.8 mm bars, and one verified journal — plus it deletes the hardware friction (608 bearing, steel nuts, pause-inserts) that the competitor scan flagged as the blocker on our previous silhouette-whitespace builds.

**Risks:** 1) Novel topology: the rotor collar is supported entirely by the 36 bridged spokes — untested stack; mitigated by both-ends-anchored 9.6 mm bridges, the OD-40 test coupon, and a 0.8 mm gap variant if sag scrapes the flange. 2) Journal fuse/grit: known failure mode of PiP journals; mitigated by the verified recipe (0.25-class clearance, 0.3 mm anti-fuse chamfers) and the 0.15/0.20/0.25 ladder. 3) Mono-color moiré contrast depends on the 1.2-1.8 mm shadow depth between grating layers — works in daylight but is weaker than two-tone; the single filament-change variant is the flagship photo configuration and must lead the listing. 4) Rim ratio as drawn is ~1.40-1.42, short of the 1.45-1.65 aspiration — bearingless PiP cannot reach Vega-ring territory; claim "highest inertia palm-size PiP" and tune with the mass-props bisection, not marketing overreach. 5) Spin duration is journal-class (tens of seconds, not bearing minutes); the design deliberately reframes decay as the payoff, but a reviewer expecting 608-bearing spin times could mark it down — the listing copy must sell the gauge, not a duration record.


## Judge summaries

- **play-value**: Judged as a fidget-community veteran with sustained-daily-play as the primary lens. Cicada 75 is the clear play-value winner: analog tilt-throttle sound/drag, wrist blips, castanet clack, and a silent 1.55-rim-ratio glide are four honest modes that create hand-to-toy conversation — the thing you actually reach for on day 30 — and its two-body axisymmetric geometry is the most first-try-printable of the field; its weakness is that its spectacle is auditory and a muted GIF grid can't sell a growl. Supernova is the best all-rounder: the rattle-to-silence transformation replays on every single flick and spin-down (unlike the Comet's fade-once-landed joke), the at-rest clatter is a legitimate secondary fidget, and the geometry is chunky, but slug-seating reliability and the defect-looking rattle carry modest risk. Pulsar Bloom owns the GIF — a non-rotating breathing square on a spinning disc is the best cover image here — but as a hand toy it is fundamentally spin-and-watch, and its five journals (including an unverified 5.2 mm mini scale), four gear meshes, phase-critical assembly, and blind cap bridges make it the biggest first-print gamble of the four. Ghost Gauge is the most passive: a beautiful, GIF-native moiré whose entire payoff is watching decay, with no tactile second act and journal-class spin times, plus a structurally novel rotor whose bearing collar rides on 36 bridged spokes — elegant, but closest to a one-trick watch-toy and mid-risk to print.
- **pizazz**: Discriminating spread across four credible candidates. Design 0 (Pulsar Bloom) owns the best 2-second GIF in the field — a non-rotating breathing square over a spinning disc is genuine corpus whitespace and the epicyclic math verifies — but it stacks five journals (four at an untested mini scale) and four gear meshes into one STL, so first-try reliability is the gamble. Design 1 (Supernova) is the best chart bet overall: a real transformation gimmick, an audible spin-down alarm, a chrome-ball HEAVY rung on the variant ladder, and the most robust geometry of the ambitious entries (verified journal, chunky rollers, no bridge over 7 mm). Design 2 (Cicada) is the best fidget toy here — four honest play modes from solid-face geometry, near-certain first print — but its headline feature is sound, which does not survive MakerWorld's silent GIF card grid; it would review brilliantly and thumbnail poorly. Design 3 (Ghost Gauge) has the judges' favorite spectacle rendered GIF-native, but hangs its journal collar off 36 bridged spokes over a 0.6 mm gap (self-flagged as untested) and its mono-color contrast is unproven; fun is a single watch-trick on journal-class spin times. If forced to pick a flagship for the leaderboard: Supernova; for pure spectacle: Pulsar Bloom, contingent on a stub-journal test coupon proving the mini diamond scale.
- **print-engineer**: Scored as an FDM print-farm engineer prioritizing first-try reliability on stock machines, cross-checked against the mesh forensics clearance data, the leaderboard success formula, and the verified build recipes. Cicada 75 is the reliability standout (verified journal at exact proven scale, solid-face teeth, 3.2 mm max bridge) and the fun leader (four analog play modes), but its sound-first wow feature is invisible in a silent cover GIF. Supernova is the best all-rounder: a genuinely novel variable-inertia mechanism built entirely from farm-safe elements (free Ø8 cylinders, 0.5 mm clearances, verified journal), with a repeatable audiovisual payoff. Pulsar Bloom owns the best GIF in the field but compounds five journals (two at unproven scales, four of them Ø5.2 blind mini diamonds) with four gear meshes that must all free on print one — the classic refund-ticket profile. Ghost Gauge has judge-validated moiré spectacle but hangs its entire rotor collar off 36 novel 9.6 mm bridges over a 0.6 mm gap above the very reticle surface the effect needs clean, and its passive journal-class spins limit sustained play.